//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Table3
    {
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //[Required]

        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int Register_no { get; set; }
        public string custname { get; set; }
        public Nullable<int> Phone_no { get; set; }
    }
}
